name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm (corepack)
        run: corepack prepare pnpm@10.0.0 --activate

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          standalone: true

      - name: PNPM version
        run: pnpm -v

      - name: Install
        run: pnpm -w install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Unit tests
        run: pnpm run test

      - name: Start backend for provider verification
        run: pnpm --filter @fleetopia/backend start & npx wait-on -t 120000 http://localhost:3001/health

      - name: Contract tests - consumer
        run: pnpm run contract:consumer

      - name: Smoke API targets
        run: pnpm run check:apis
        env:
          API_BASE: http://localhost:3001

      - name: Contract tests - provider
        run: pnpm run contract:provider
        env:
          PROVIDER_BASE_URL: http://localhost:3001

      - name: Stop backend
        if: always()
        run: pkill -f "dist/server.js" || true

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: E2E tests
        run: pnpm run test:e2e

  validate-db-logs:
    name: validate-db-logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install pnpm (corepack)
        run: corepack prepare pnpm@10.0.0 --activate
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          standalone: true
      - name: PNPM version
        run: pnpm -v
      - name: Install
        run: pnpm -w install --frozen-lockfile
      - name: Validate DB logs
        run: pnpm run validate:db-logs

  check-apis:
    name: check-apis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install pnpm (corepack)
        run: corepack prepare pnpm@10.0.0 --activate
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          standalone: true
      - name: PNPM version
        run: pnpm -v
      - name: Install
        run: pnpm -w install --frozen-lockfile
      - name: Start backend
        run: pnpm --filter @fleetopia/backend start & npx wait-on -t 120000 http://localhost:3001/health
      - name: Smoke API targets
        run: pnpm run check:apis
        env:
          API_BASE: http://localhost:3001
      - name: Stop backend
        if: always()
        run: pkill -f "dist/server.js" || true
