name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

env:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_SENTRY_DSN_FRONTEND: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_FRONTEND }}

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm (global)
        run: npm i -g pnpm@10

      - name: Verify pnpm
        run: pnpm -v

      - name: Install deps (workspace)
        run: pnpm install -w --no-frozen-lockfile

      - name: Install + Build contracts
        run: |
          pnpm --filter @fleetopia/contracts install --no-frozen-lockfile || true
          pnpm --filter @fleetopia/contracts build || true

      - name: Install backend deps
        run: pnpm --filter @fleetopia/backend install --no-frozen-lockfile

      - name: Typecheck (web only)
        run: pnpm --filter @fleetopia/web run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Build (root)
        run: pnpm run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_SENTRY_DSN_FRONTEND: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_FRONTEND }}

      - name: Build backend
        run: pnpm --filter @fleetopia/backend build

      - name: Unit tests
        run: pnpm run test

      - name: Start backend
        run: pnpm --filter @fleetopia/backend build && pnpm --filter @fleetopia/backend start & npx wait-on -t 120000 http://localhost:3001/health

      - name: Contract tests - consumer
        run: pnpm run contract:consumer

      - name: Smoke API targets
        run: pnpm run check:apis
        env:
          API_BASE: http://localhost:3001

      - name: Contract tests - provider
        run: pnpm run contract:provider
        env:
          PROVIDER_BASE_URL: http://localhost:3001

      - name: Stop backend
        if: always()
        run: pkill -f "dist/server.js" || true

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: E2E tests
        run: pnpm run test:e2e
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_SENTRY_DSN_FRONTEND: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_FRONTEND }}

  validate-db-logs:
    name: validate-db-logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm (global)
        run: npm i -g pnpm@10
      - name: Verify pnpm
        run: pnpm -v
      - name: Install deps (workspace)
        run: pnpm install -w --no-frozen-lockfile
      - name: Validate DB logs
        run: pnpm run validate:db-logs

  check-apis:
    name: check-apis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm (global)
        run: npm i -g pnpm@10
      - name: Verify pnpm
        run: pnpm -v
      - name: Install deps (workspace)
        run: pnpm install -w --no-frozen-lockfile
      - name: Install backend deps
        run: pnpm --filter @fleetopia/backend install --no-frozen-lockfile
      - name: Build backend
        run: pnpm --filter @fleetopia/backend build
      - name: Start backend
        run: pnpm --filter @fleetopia/backend build && pnpm --filter @fleetopia/backend start & npx wait-on -t 120000 http://localhost:3001/health
      - name: Smoke API targets
        run: pnpm run check:apis
        env:
          API_BASE: http://localhost:3001
      - name: Stop backend
        if: always()
        run: pkill -f "dist/server.js" || true
